### Control flow

In [ ]:
# Variable assignment ----------------------------
a,b,c=5,10,15
print(a)
print(b)
print(c)

# Data types ----------------------------
x = 1
y = 2.8
z = 1j
a= "True"
b=True

print(type(x))
print(type(y))
print(type(z))
print(type(a))
print(type(b))

5
10
15
<class 'int'>
<class 'float'>
<class 'complex'>
<class 'str'>
<class 'bool'>

**String functions:**
* strip() – remove whitespaces
* len() – no of characters in string
* lower()
* upper()
* replace() – replace one string with another
* split() – split using a character
* input() – to accept user input from keyboard

In [ ]:
## String functions ----------------------------
a = 'Hello, World!'
print(a[1])
b = "Hello, World!"
print(b[2:5])
a = " Hello, World! "
print(a.strip()) # returns "Hello, World!"
a = "Hello, World!"
print(len(a))
a = "Hello, World!"
print(a.lower())
a = "Hello, World!"
print(a.upper())
a = "Hello, World!"
print(a.replace("H", "J"))
a = "Hello, World!"
print(a.split(",")) # returns ['Hello', ' World!']
print("Enter your name:")
x = input()
print("Hello, " + x)

e
llo
Hello, World!
13
hello, world!
HELLO, WORLD!
Jello, World!
['Hello', ' World!']
Enter your name:
fdfd
Hello,  fdfd

**If Else**

In [ ]:
#-------------------if else

a = 33
b = 200
if (b > a):
  print("b is greater than a");

a = 33
b = 200
if b > a:
  print("b is greater than a") # you will get an error without indentation

a = 33
b = 35 # change value and see
if a == b:
  print("a and b are equal")
else:
  print("a and b are not equal")

a = 200
b = 33 # change value and see
if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")
else:
  print("a is greater than b")

#shortcut syntax
if a > b: print("a is greater than b")

print("A") if a > b else print("B")

a = 200
b = 33 # change value and see
c=300
if a > b and c > a:
  print("Both conditions are True")

if a > b or a > c:
  print("At least one of the conditions are True")

b is greater than a
b is greater than a
a and b are not equal
a is greater than b
a is greater than b
A
Both conditions are True
At least one of the conditions are True

**While loop**

In [ ]:
#-------------------while loop
i = 1
while i < 6:
  print(i)
  i =i+ 1

0
1
2
3
4
5

**Break statement**

In [ ]:
#------------------break example
i = 1
while i < 6:
  print(i)
  if i == 3:
    break
  i += 1

1
2
3

**for loop**

In [ ]:
print(range(6))
#-------------------for loop
for x in range(6):
  print(x)
print('next loop')

for x in range(2, 6):
  print(x)
print('next loop')

for x in range(2, 30, 3):
  print(x)
print('next loop')

for x in range(6):
  print(x)
  #break
else:
  print("Finally finished!")

range(0, 6)
0
1
2
3
4
5
next loop
2
3
4
5
next loop
2
5
8
11
14
17
20
23
26
29
next loop
0

### Collection data types



---

**Lists**

* len() - returns no of elements
* append() - Adds an element at the end of the list
* insert() - Adds an element at the specified position
* remove() - Removes the item with the specified value
* pop() -  removes the specified index, (or the last item if index is not specified)
* del – can be used for a member or the list itself
* clear() - Removes all the elements from the list
* count() - Returns the number of elements with the specified value
* extend() - Add the elements of a list (or any iterable), to the end of the current list
* index() - Returns the index of the first element with the specified value
* reverse()
* sort()

In [ ]:
## Lists--------------------

for x in "banana":
  print(x)

thislist = ["apple", "banana", "cherry"]
print(thislist)

thislist = ["apple", "banana", "cherry"]
print(thislist[1])

thislist = ["apple", "banana", "cherry"]
thislist[1] = "blackcurrant"
print(thislist)

thislist = ["apple", "banana", "cherry"]
for x in thislist:
  print(x)

thislist = ["apple", "banana", "cherry"]
print(len(thislist))

thislist = ["apple", "banana", "cherry"]
thislist.append("orange")
print(thislist)

thislist = ["apple", "banana", "cherry"]
thislist.insert(1, "orange")
print(thislist)

thislist = ["apple", "banana", "cherry"]
thislist.remove("banana")
print(thislist)

thislist = ["apple", "banana", "cherry"]
thislist.pop() # can take index as well (pop(1))
print(thislist)

thislist = ["apple", "banana", "cherry"]
del thislist
#print(thislist) #this will cause an error because "thislist" no longer exists.

thislist = ["apple", "banana", "cherry"]
thislist.clear()
print(thislist)

thislist = ["apple", "banana", "apple"]
print(thislist.count("apple"))

thislist1 = ["apple", "banana", 3]
thislist2 = ("fig", "guava")
thislist1.extend(thislist2)
print(thislist1)

thislist = ["apple", "banana", "cherry"]
print(thislist.index("banana"))

thislist = ["apple", "banana", "cherry"]
thislist.reverse()
print(thislist)

thislist = ["apple", "cherry", "banana"]
thislist.sort()
print(thislist)

b
a
n
a
n
a
['apple', 'banana', 'cherry']
banana
['apple', 'blackcurrant', 'cherry']
apple
banana
cherry
3
['apple', 'banana', 'cherry', 'orange']
['apple', 'orange', 'banana', 'cherry']
['apple', 'cherry']
['apple', 'banana']
[]
2
['apple', 'banana', 3, 'fig', 'guava']
1
['cherry', 'banana', 'apple']
['cherry', 'banana', 'apple']

**Tuples**

In [ ]:
## Tuples--------------------

thistuple = ('physics', 'chemistry', 1997, 2000)
print(thistuple)

thistuple = ('physics', 'chemistry', 1997, 2000)
print(thistuple[1])

thistuple = ('physics', 'chemistry', 1997, 2000)
#thistuple[1] = 'abc' # raises error
# The values will remain the same:
print(thistuple)

thistuple = ('physics', 'chemistry', 1997, 2000)
for x in thistuple:
  print(x)

thistuple = ('physics', 'chemistry', 1997, 2000)
print(len(thistuple))

thistuple = ('physics', 'chemistry', 1997, 2000)
print(thistuple.index(1997))

thistuple = ('physics', 'chemistry', 1997, 2000)
del thistuple
#print(thistuple) #this will raise an error because the tuple no longer exists

('physics', 'chemistry', 1997, 2000)
chemistry
('physics', 'chemistry', 1997, 2000)
physics
chemistry
1997
2000
4
2

**Sets**

* difference() - Returns a set containing the difference between two or more sets
* intersection() - Returns a set, that is the intersection of two other sets
* isdisjoint() - Returns True if the intersection is null
* issubset() - Returns whether another set contains this set or not
* issuperset() - Returns whether this set contains another set or not
* union() - Return a set containing the union of sets

In [ ]:
## Sets--------------------

thisset = {1,2,3}
print(thisset)

thisset = {1,2,3}

for x in thisset:
  print(x)

thisset = {1,2,3}
print(4 in thisset)

thisset = {1,2,3}
thisset.add(4)
print(thisset)

thisset = {1,2,3}
thisset.update([4,5,6])
print(thisset)

thisset = {1,2,3}
print(len(thisset))

thisset = {1,2,3}
thisset.remove(2)
print(thisset)


thisset = {1,2,3}
thisset.clear()
print(thisset)

thisset = {1,2,3}
del thisset
#print(thisset)

# initialize A and B
A = {1, 2, 3, 4, 5}
B = {4, 5, 6, 7, 8}
C = {1,2}

print(A.union(B))
print(A.intersection(B))
print(A.isdisjoint(C))
print(A.issuperset(C))
print(A.issubset(C))
print(A.difference(B))
print(B.difference(A))

{1, 2, 3}
1
2
3
False
{1, 2, 3, 4}
{1, 2, 3, 4, 5, 6}
3
{1, 3}
set()
{1, 2, 3, 4, 5, 6, 7, 8}
{4, 5}
False
True
False
{1, 2, 3}
{8, 6, 7}

**Dictionaries**

* items() - Returns a list containing the a tuple for each key value pair
* keys() - Returns a list containing the dictionary's keys
* values() - Returns a list of all the values in the dictionary

In [ ]:
## Dictionaries--------------------

thisdict =	{
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(thisdict)
x = thisdict["model"]
print(x)

thisdict =	{
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
thisdict["year"] = 2018

for x in thisdict:
  print(x)

for x in thisdict.keys():
  print(x)

for x in thisdict.values():
  print(x)

for x, y in thisdict.items():
  print(x, y)

print(len(thisdict))

thisdict =	{
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
thisdict["color"] = "red" # add new one
print(thisdict)

thisdict =	{
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
thisdict.pop("model")
print(thisdict)

thisdict =	{
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
del thisdict
#print(thisdict) #this will cause an error because "thislist" no longer exists.

thisdict =	{
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
thisdict.clear()
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}
Mustang
brand
model
year
brand
model
year
Ford
Mustang
2018
brand Ford
model Mustang
year 2018
3
{'brand': 'Ford', 'model': 'Mustang', 'year': 1964, 'color': 'red'}
{'brand': 'Ford', 'year': 1964}
{}

In [ ]:
thisdict =	{
  "brand": "Ford",
  "model": "Mustang",
  "year": [1,2,3]
}

ls=[100,200,thisdict]
print(ls)
print(ls[2]["year"][1])

[100, 200, {'brand': 'Ford', 'model': 'Mustang', 'year': [1, 2, 3]}]
2

More examples

https://www.programiz.com/python-programming/examples

### Functions

In [ ]:
# Required arguments
def simple_interest(p,t,r):
    return (p*t*r)/100

# same order
print("Simple Interest: ",simple_interest(2500,6,2))

# different order
print("Simple Interest: ",simple_interest(t=10,r=10,p=1900))

Simple Interest:  300.0
Simple Interest:  1900.0

In [ ]:
# Default arguments
def printme(name,age=22):
    print("My name is",name,"and age is",age)

printme("john")
printme(age = 10,name="David")

My name is john and age is 22
My name is David and age is 10

In [ ]:
# Variable length arguments
def printme(*names):
    print("type of passed argument is ",type(names))

    for name in names:
        print(name)

printme("john","David")
printme("john","David","smith","nick")

type of passed argument is  <class 'tuple'>
john
David
type of passed argument is  <class 'tuple'>
john
David
smith
nick

**Global and Local variables**

In python, the variables are defined with the two types of scopes.

* Global variables
* Local variables

* The variable defined outside any function is known to have a global scope
* whereas the variable defined inside a function is known to have a local scope.

In [ ]:
x = "awesome"
def myfunc():
  x = "fantastic"
  print("Python is " + x)

print("Python is " + x)
myfunc()

Python is awesome
Python is fantastic

In [ ]:
def myfuncNew():
  global x
  x = "newval"

print("Python is " + x)
myfuncNew()
print("Python is " + x)

Python is awesome
Python is newval

### Object Oriented Programming

In [ ]:
class Employee:
    def __init__(self,name,id):
        self.id = id
        self.name = name
    def display(self):
        print("ID: %d \nName: %s"%(self.id,self.name))

emp1 = Employee("John",101)
emp2 = Employee("David",102)

emp1.display()
emp2.display()

ID: 101
Name: John
ID: 102
Name: David

In [ ]:
# Class and instance variablles and methods -------------------------
class Student:
    count = 0  # this is a class level variable

    def disp(): # this is a class level function
        print("at class level ")
    def __init__(self):
        Student.count = Student.count + 1
    def display(self):
        print("at object level")

s1=Student()
s2=Student()
s3=Student()

print("The number of students:",Student.count)

Student.disp()
s1.display()

The number of students: 3
at class level
at object level

**Inheritance**

* Single Inheritance
* Multiple Inheritance
* Multilevel Inheritance
* Hierarchical Inheritance
* Hybrid Inheritance

In [ ]:
# Single inheritance ------------------

class Animal:
    def __init__(self):
      print('constructor at parent level')
    def speak(self):
        print("Animal Speaking")
#child class Dog inherits the base class Animal
class Dog(Animal):
    def __init__(self):
      print('constructor at child level')
      super().__init__()
    def bark(self):
        print("dog barking")
d = Dog()
d.bark()
d.speak()

constructor at child level
constructor at parent level
dog barking
Animal Speaking

In [ ]:
# Multi - level inheritance -----------------------

class Animal:
    def speak(self):
        print("Animal Speaking")
#The child class Dog inherits the base class Animal
class Dog(Animal):
    def bark(self):
        print("dog barking")
#The child class Dogchild inherits another child class Dog
class DogChild(Dog):
    def eat(self):
        print("Eating bread...")
d = DogChild()
d.bark()
d.speak()
d.eat()

dog barking
Animal Speaking
Eating bread...

In [ ]:
# Multiple inheritance -----------------------

class Calculation1:
    def Summation(self,a,b):
        return a+b
    def disp(self):
      print('Calculation1')
class Calculation2:
    def Multiplication(self,a,b):
        return a*b
    def disp(self):
      print('Calculation2')
class Derived(Calculation1,Calculation2):
    def Divide(self,a,b):
        return a/b
d = Derived()
# Better way
#c1=Calculation1()
#c2=Calculation2()
#c2.disp()
print(d.Summation(10,20))
print(d.Multiplication(10,20))
print(d.Divide(10,20))
d.disp()

30
200
0.5
Calculation2

**Polymorphism**

* The ability to appear in many forms.

* In object-oriented programming, polymorphism refers to a programming language's ability to process objects differently depending on their data type or class.

* Method Overloading and Method Overriding help here.

* Polymorphism allows for flexibility and loose coupling so that code can be extended and easily maintained over time.

* The right class / object to be used is determined at Runtime based on what actual object is instantiated.

https://refactoring.guru/replace-conditional-with-polymorphism

In [ ]:
# Method overloading --------------------------
# Java and C++ style overloading not possible in python
class Student:
    def hello(self, name=None):
        if name is not None:
            print('Hey ' + name)
        else:
            print('Hey ')

# Creating a class instance
std = Student()

# Call the method
std.hello()

# Call the method and pass a parameter
std.hello('Nicholas')

Hey
Hey Nicholas

In [ ]:
# Method overriding --------------------------
class Mobile():
    def IncreaseBrightness(self):
        print("Mobile Brightness")

class Samsung(Mobile):
  pass

class Nokia(Mobile):  # remove inheritance and see too
    def IncreaseBrightness(self):
        #super().IncreaseBrightness()
        print("Nokia Brightness")

#d = Mobile()
#d= Samsung() # fine with base class functionality
d = Nokia()   # NOT fine with base class functionality
d.IncreaseBrightness()

Mobile Brightness
Nokia Brightness

### File access

The open() function takes two parameters; filename, and mode.

* file.close()
* file.read([size])
* file.readline([size])
* file.write()

There are four different methods (modes) for opening a file:

* "r" - Read - Default value. Opens a file for reading, error if the file does not exist
* "a" - Append - Opens a file for appending, creates the file if it does not exist
* "w" - Write - Opens a file for writing, creates the file if it does not exist
* "x" - Create - Creates the specified file, returns an error if the file exists

In [ ]:
# Create a file

f= open("demofile.txt", "w")
f.write("Line number one")
f.write("\n")
f.write("Line number two")
f.close()

In [ ]:
# Read file in different ways
f = open("demofile.txt", "r")
# use rb for 1 and 2 whence (2nd param) in seek. 0-start, 1- current pos, 2- EOF
print(type(f))

fl=f.read() #try with 20
print(type(fl))
print(len(fl))

#f.seek(0,0) # place file pointer wherever required. first param is offset
print(f.read()) # won't print anything till we open it again

<class '_io.BufferedReader'>
<class 'bytes'>
31
b'r two'

In [ ]:
f = open("demofile.txt", "r")
print(f.read(5))
print(f.read(5))

f = open("demofile.txt", "r")
print(f.readline())
print(f.readline(13))

f = open("demofile.txt", "r")
for x in f:
  print(x)

Line
numbe
Line number one

Line number t
Line number one

Line number two

In [ ]:
# Append data to file
f = open("demofile.txt", "a")
f.write("\nNow the file has more content")
f.close()

f = open("demofile.txt", "r")
print(f.read())

Line number one
Line number two
Now the file has more content
Now the file has more content

In [ ]:
import os # Operating System module
os.remove("demofile.txt")
# https://www.geeksforgeeks.org/os-module-python-examples/

### Exception handling

In [ ]:
# without handling exceptions
a = 5
b = 0
c = a/b
print(c)

# next code:
print("Hi I am in next part of the program")

ZeroDivisionError: division by zero

In [ ]:
# handling exceptions
try:
    a = 5
    b = 0 # change it to 1 and see
    c = a/b
    print(c)
except:
    print("can't divide by zero")
else:
    print("Hi I am else block")

# next code:
print("Hi I am in next part of the program")

5.0
Hi I am else block
Hi I am in next part of the program

In [ ]:
# handling multiple exceptions
try:
    a = 5
    b = 0 # change it to 1 and see
    c = a/b
    print(c)
    #f=open('demofile.txt')
    d=e  # remove the comment and see
except ZeroDivisionError:
    print("can't divide by zero")
except NameError as ne:
    print("Name has a problem")
    print(ne)
except BaseException as ex:
    print("Some other problem")
    print(type(ex))
    print(ex)
else:
    print("Hi I am else block")

5.0
Some other problem
<class 'FileNotFoundError'>
[Errno 2] No such file or directory: 'demofile.txt'

In [ ]:
# using finally
try:
  print(5/0) #try with 5/0
except:
  print("Something went wrong")
finally:
  print("The 'try except' is finished")

Something went wrong
The 'try except' is finished

In [ ]:
# custom exceptions
class ErrorInCode(Exception):
    def __init__(self, data):
        self.data = data
    def custexp1(self):
      print('custexp1')
    def custexp2(self):
      print('custexp2')

try:
    raise ErrorInCode(2000)
except ErrorInCode as ae:
    if(ae.data==2000):
      ae.custexp1()
    if(ae.data==3000):
      ae.custexp2()

custexp1

### Data Access using SQLite

In [ ]:
# Create table
import sqlite3
conn = sqlite3.connect('test.db')
print(type(conn))

# Create table
cr=conn.execute('''CREATE TABLE COMPANY
         (ID INT PRIMARY KEY     NOT NULL,
         NAME           TEXT    NOT NULL,
         AGE            INT     NOT NULL,
         ADDRESS        CHAR(50),
         SALARY         REAL);''')
print ("Table created successfully");
print(cr)
conn.close()

<class 'sqlite3.Connection'>
Table created successfully
<sqlite3.Cursor object at 0x7c6a804cb6c0>

In [ ]:
# Insert values
conn = sqlite3.connect('test.db')
cr=conn.cursor()
# instead of cr we use conn directly
cr.execute('''INSERT INTO COMPANY (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (1, 'Paul', 32, 'California', 20000.00 )''')
conn.execute("INSERT INTO COMPANY (ID,NAME,AGE,ADDRESS,SALARY) \
      VALUES (2, 'Allen', 25, 'Texas', 15000.00 )")
conn.execute("INSERT INTO COMPANY (ID,NAME,AGE,ADDRESS,SALARY) \
      VALUES (3, 'Teddy', 23, 'Norway', 20000.00 )")

a=4
b='Mark'
c=25
d='Rich-Mond'
e=65000
cr.execute("INSERT INTO COMPANY (ID,NAME,AGE,ADDRESS,SALARY) \
      VALUES (?, ?, ?, ?, ? )",(a,b,c,d,e))
conn.commit()
print ("Records created successfully")
conn.close()

Records created successfully

In [ ]:
# Fetch values
conn = sqlite3.connect('test.db')
print ("Opened database successfully");
cursor = conn.execute("SELECT id, name, address, salary from COMPANY")
# can also call exeutescript()
print(type(cursor))
for row in cursor: # can also use fetchmany(), fetchone() etc.
   print ("ID = ", row[0])
   print ("NAME = ", row[1])
   print ("ADDRESS = ", row[2])
   print ("SALARY = ", row[3], "\n")
print ("Rows fetched successfully")
x=3
cursor = conn.execute("SELECT id, name, address, salary from COMPANY where id=?",(x,))
for row in cursor:
   print(row)
   print ("ID = ", row[0])
   print ("NAME = ", row[1])
   print ("ADDRESS = ", row[2])
   print ("SALARY = ", row[3], "\n")
print ("1 row fetched successfully")
conn.close()

Opened database successfully
<class 'sqlite3.Cursor'>
ID =  1
NAME =  Paul
ADDRESS =  California
SALARY =  20000.0

ID =  2
NAME =  Allen
ADDRESS =  Texas
SALARY =  15000.0

ID =  3
NAME =  Teddy
ADDRESS =  Norway
SALARY =  20000.0

ID =  4
NAME =  Mark
ADDRESS =  Rich-Mond
SALARY =  65000.0

Rows fetched successfully
(3, 'Teddy', 'Norway', 20000.0)
ID =  3
NAME =  Teddy
ADDRESS =  Norway
SALARY =  20000.0

1 row fetched successfully

In [ ]:
# Update values
conn = sqlite3.connect('test.db')
print ("Opened database successfully");
temp=conn.execute("UPDATE COMPANY set SALARY = 25000.00 where ID = 1")
print(temp)
conn.commit()
print ("Total number of rows updated :", conn.total_changes)
cursor = conn.execute("SELECT id, name, address, salary from COMPANY")
for row in cursor:
   print ("ID = ", row[0])
   print ("NAME = ", row[1])
   print ("ADDRESS = ", row[2])
   print ("SALARY = ", row[3], "\n")
print ("Results shown successfully");
conn.close()

Opened database successfully
<sqlite3.Cursor object at 0x7b2711086d40>
Total number of rows updated : 1
ID =  1
NAME =  Paul
ADDRESS =  California
SALARY =  25000.0

ID =  2
NAME =  Allen
ADDRESS =  Texas
SALARY =  15000.0

ID =  3
NAME =  Teddy
ADDRESS =  Norway
SALARY =  20000.0

ID =  4
NAME =  Mark
ADDRESS =  Rich-Mond
SALARY =  65000.0

Results shown successfully

In [ ]:
# Delete values
conn = sqlite3.connect('test.db')
print ("Opened database successfully");
x=2
conn.execute("DELETE from COMPANY where ID = ?",(x,))
conn.commit()
print ("Total number of rows deleted :", conn.total_changes)
cursor = conn.execute("SELECT id, name, address, salary from COMPANY")
for row in cursor:
   print ("ID = ", row[0])
   print ("NAME = ", row[1])
   print ("ADDRESS = ", row[2])
   print ("SALARY = ", row[3], "\n")
print ("Deletion done successfully");
conn.close()

Opened database successfully
Total number of rows deleted : 1
ID =  1
NAME =  Paul
ADDRESS =  California
SALARY =  25000.0

ID =  3
NAME =  Teddy
ADDRESS =  Norway
SALARY =  20000.0

ID =  4
NAME =  Mark
ADDRESS =  Rich-Mond
SALARY =  65000.0

Deletion done successfully

In [ ]:
import pandas as pd
conn = sqlite3.connect('test.db')
# dataframe is a structure to hold tabular data
df = pd.read_sql_query("select * from COMPANY", conn)

df.head()

### Miscellaneous

**Regular expressions**

In [ ]:
import re

txt = "The rain in Spain"

# it will return a Match object if the pattern is found. otherwise it will return None
x = re.search("^The.*Spain$", txt)

if (x):
  print(type(x))
  print("YES! We have a match!")
else:
  print("No match")

<class 're.Match'>
YES! We have a match!

**Lambda functions**

* A lambda function is an anonymous inline function. It is defined without a name. This can be used if you need a nameless function for a short period of time.  Can work with single expression only

In [ ]:
fun = lambda a, b : a * b
print(fun(5, 6))

30

**List Comprehension**

* List comprehensions are used for creating new lists from other iterables.
* As list comprehensions return lists, they consist of brackets containing the expression, which is executed for each element along with the for to iterate over each element.

In [ ]:
numbers = (1, 2, 3, 4)

squares = [n**2 for n in numbers if n%2==0]

print(squares)

[4, 16]

**Working with JSON**

* JSON is a syntax for storing and exchanging data.
* It is a standardized format people use to pass data around. XML is similar.

* JavaScript Object Notation was inspired by a subset of the JavaScript
* It’s easy for both humans and machines to create and understand.

* The process of encoding JSON is called serialization.
* It is the transformation of data into a series of bytes to be stored or transmitted across a network.
* Deserialization is the reverse process.

* The json library in Python exposes the dump() method for writing data to files and dumps() method for writing to a Python string.

* json library has load() and loads() for turning JSON encoded data into Python objects.

* https://www.digitalocean.com/community/tutorials/an-introduction-to-json

In [ ]:
df.set_index('ID', inplace=True)
df.head()

     NAME  AGE     ADDRESS   SALARY
ID
1    Paul   32  California  20000.0
2   Allen   25       Texas  15000.0
3   Teddy   23      Norway  20000.0
4    Mark   25   Rich-Mond  65000.0

In [ ]:
df.to_json('js.json')

In [ ]:
data={
    "firstName": "Alex",
    "lastName": "Smith",
    "age": 35,
    "children": [
        {
            "firstName": "Alice",
            "age": 6
        },
        {
            "firstName": "Bob",
            "age": 8
        }
    ]
}

import json
# Write JSON
with open("data_file.json", "w") as write_file:
    json.dump(data, write_file)

json_string = json.dumps(data)
print(json_string)

{"firstName": "Alex", "lastName": "Smith", "age": 35, "children": [{"firstName": "Alice", "age": 6}, {"firstName": "Bob", "age": 8}]}

In [ ]:
# Read JSON
with open("data_file.json", "r") as read_file:
    read_data = json.load(read_file)

read_data_str = json.loads(json_string)

print(type(read_data_str))
print(read_data_str["age"])

<class 'dict'>
35

* We will use JSONPlaceholder, a source of fake JSON data for practice purpose explore the data in the url
* We need to make an API request to the JSONPlaceholder service, so just use the requests package

* The requests module allows you to send HTTP requests using Python.
* The HTTP request returns a Response Object with all the  response data (content, encoding, status, etc)

In [ ]:
import json
import requests

response = requests.get("https://jsonplaceholder.typicode.com/todos")
todos = json.loads(response.text)
print(type(todos))
print(todos[:3])

count=0
for todo in todos:
    if todo["completed"]:
        # Increment the existing user's count.
        count+= 1
print(count)

<class 'list'>
[{'userId': 1, 'id': 1, 'title': 'delectus aut autem', 'completed': False}, {'userId': 1, 'id': 2, 'title': 'quis ut nam facilis et officia qui', 'completed': False}, {'userId': 1, 'id': 3, 'title': 'fugiat veniam minus', 'completed': False}]
90

In [ ]:
import pandas as pd

with open("data_file_new.json", "w") as write_file:
    json.dump(todos, write_file)

In [ ]:
df = pd.read_json('data_file_new.json')
df.head()

   userId  id                                              title  completed
0       1   1                                 delectus aut autem      False
1       1   2                 quis ut nam facilis et officia qui      False
2       1   3                                fugiat veniam minus      False
3       1   4                                   et porro tempora       True
4       1   5  laboriosam mollitia et enim quasi adipisci qui...      False

### Web API programming and Web scraping

In [1]:
# Install the necessary libraries: requests for making HTTP requests and beautifulsoup4 for parsing HTML.
!pip install requests beautifulsoup4

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (4.13.5)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2025.8.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (2.8)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (4.15.0)

Now, let's use `requests` to fetch the content of a webpage.

In [3]:
# Import the requests library
import requests

# Define the URL of the webpage to fetch
url = 'http://example.com' # You can replace this with any URL

# Use a try-except block to handle potential errors during the request
try:
    # Make a GET request to the URL
    response = requests.get(url)
    # Raise an exception for bad status codes (e.g., 404 Not Found, 500 Internal Server Error)
    response.raise_for_status()
    # Get the HTML content from the response
    html_content = response.text
    # Print a success message
    print("Successfully fetched the webpage content!")
    # Print the first 500 characters of the HTML content
    print(html_content[:500])
except requests.exceptions.RequestException as e:
    # If an error occurs during the request, print an error message
    print(f"Error fetching the webpage: {e}")

Successfully fetched the webpage content!
<!doctype html>
<html>
<head>
    <title>Example Domain</title>

    <meta charset="utf-8" />
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style type="text/css">
    body {
        background-color: #f0f0f2;
        margin: 0;
        padding: 0;
        font-family: -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;

Next, we'll use `BeautifulSoup` to parse the HTML content and extract information.

In [4]:
# Import the BeautifulSoup class from the bs4 library
from bs4 import BeautifulSoup

# Check if the html_content variable exists and is not empty
if 'html_content' in locals(): # Check if html_content was successfully fetched
    # Create a BeautifulSoup object by parsing the HTML content
    soup = BeautifulSoup(html_content, 'html.parser')

    # Example 1: Get the title of the page
    # The title is found within the <title> tag
    title = soup.title.string
    print(f"\nPage Title: {title}")

    # Example 2: Find all the paragraph tags
    # find_all() returns a list of all elements matching the tag
    paragraphs = soup.find_all('p')
    print(f"\nNumber of paragraph tags: {len(paragraphs)}")
    # If there are any paragraphs, print the text of the first one
    if paragraphs:
        print("First paragraph:")
        print(paragraphs[0].text)
else:
    # If html_content was not fetched, print an error message
    print("Could not parse HTML as the webpage content was not fetched.")

Page Title: Example Domain

Number of paragraph tags: 2
First paragraph:
This domain is for use in illustrative examples in documents. You may use this
    domain in literature without prior coordination or asking for permission.

Here are some more examples demonstrating how to use `BeautifulSoup` to parse HTML and extract data:

In [16]:
# Import necessary libraries
from bs4 import BeautifulSoup
import requests

# Fetching a more complex page for demonstration
url = 'http://quotes.toscrape.com/' # A website specifically designed for scraping examples
# Use a try-except block to handle potential errors
try:
    # Make a GET request to the URL
    response = requests.get(url)
    # Raise an exception for bad status codes
    response.raise_for_status()
    # Get the HTML content
    html_content = response.text
    # Create a BeautifulSoup object to parse the HTML
    soup = BeautifulSoup(html_content, 'html.parser')

    print(f"Successfully fetched and parsed: {url}")

    # Example 1: Finding the first element of a specific tag
    print("\n--- Example 1: Finding the first <div> tag ---")
    # find() returns the first element that matches the tag
    first_div = soup.find('div')
    # Print a snippet of the found div using prettify() for formatted output
    print(first_div.prettify()[:200] + "...") # Print a snippet

    # Example 2: Finding all <span> tags with class 'text' (the quotes)
    print("\n--- Example 2: Finding all <span> tags with class 'text' (the quotes) ---")
    # find_all() returns a list of all elements that match the tag and attributes
    quotes = soup.find_all('span', class_='text')
    print(f"Number of quotes found: {len(quotes)}")
    # If quotes are found, print the text of the first 3
    if quotes:
        print("First 3 quotes:")
        for i, quote in enumerate(quotes[:3]):
            print(f"{i+1}. {quote.text}")

    # Example 3: Navigating the parse tree (finding the author of a quote)
    print("\n--- Example 3: Finding the author of the first quote ---")
    # Find the first quote element
    first_quote_element = soup.find('span', class_='text')
    if first_quote_element:
        # The author is in a <small> tag within the same parent <div>, find the element with class 'author'
        # The author is within the same parent div as the quote, but not necessarily a sibling.
        # We can find the parent div first, and then search for the author within that div.
        parent_div = first_quote_element.find_parent('div', class_='quote')
        if parent_div:
            author_element = parent_div.find('small', class_='author')
            if author_element:
                print(f"Author of the first quote: {author_element.text}")
            else:
                print("Author element not found within the parent div.")
        else:
            print("Parent div with class 'quote' not found for the first quote.")
    else:
        print("First quote element not found.")


except requests.exceptions.RequestException as e:
    # Handle errors during the request
    print(f"Error fetching the webpage: {e}")
except Exception as e:
    # Handle any other errors during parsing
    print(f"An error occurred during parsing: {e}")

Successfully fetched and parsed: http://quotes.toscrape.com/

--- Example 1: Finding the first <div> tag ---
<div class="container">
 <div class="row header-box">
  <div class="col-md-8">
   <h1>
    <a href="/" style="text-decoration: none">
     Quotes to Scrape
    </a>
   </h1>
  </div>
  <div class="col...

--- Example 2: Finding all <span> tags with class 'text' (the quotes) ---
Number of quotes found: 10
First 3 quotes:
1. “The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”
2. “It is our choices, Harry, that show what we truly are, far more than our abilities.”
3. “There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”

--- Example 3: Finding the author of the first quote ---
Author of the first quote: Albert Einstein